# Generated by Django 5.1.2 on 2024-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_producto_fecha_creacion_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='imagen_perfil',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
